services:
  klukka:
    image: 1manprojects/klukka
    depends_on:
      - postgres
    environment:
      - APPLICATION_URL=
      - ADMIN_USER_NAME=
      - ADMIN_PASSWORD=
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_USER=klukka
      - DATABASE_PASSWORD=CHANGEME
      - DATABASE_NAME=klukka
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_AUTH=true
      - SMTP_SSL=true
      - SMTP_USER=
      - SMTP_PASSWORD=
    volumes:
      - ./klukka_data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=klukka
      - POSTGRES_USER=klukka
      - POSTGRES_PASSWORD=CHANGEME
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
